### ISSUE TITLE
Definition of M

### ISSUE THREAD

**Issue by rxian** [chenw20/BiasScore#1]
According to the paper, M is limited to 5000.  So should the `max` actually be `min` in the following line?

https://github.com/chenw20/BiasScore/blob/b744718f95039902144bd039e9266c4c3ee8c779/postprocess_eo.py#L162

**Comment by chenw20** [comment]
Hi Ruicheng, thanks for pointing out the typo. Indeed, it should be ```min```. I have updated the code accordingly.

**Comment by rxian** [comment]
> Hi Ruicheng, thanks for pointing out the typo. Indeed, it should be `min`. I have updated the code accordingly.

Thanks!  Would it affect the results in the paper?

**Comment by chenw20** [comment]
> > Hi Ruicheng, thanks for pointing out the typo. Indeed, it should be `min`. I have updated the code accordingly.
> 
> Thanks! Would it affect the results in the paper?

I just checked the original code used to run the experiments: we simply used ```M = 5000``` there. The typo in the uploaded code was introduced when I cleaned the code. So it doesn't affect the reported results in the paper.
